site_name: Graby Docs
site_url: https://wpgraby.com
nav:
    - Home: index.md
    - About: about.md
    - License: license.md
theme:
    name: material
    language: vi
extra:
  alternate:
    - name: Tiếng Việt
      link: /
      lang: vi
    - name: Deutsch
      link: /de/
      lang: de    
